# Generated by Django 5.0.7 on 2024-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_date_alter_emp_job_alter_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='years',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
